version: "3.7"
services:
  mongo:
    container_name: mongo
    restart: always
    image: mongo
    volumes:
      - data:/data/db
    ports:
      - 27017:27017
  api:
    container_name: api
    restart: always
    build:
      context: .
      args:
        - NODE_ENV=NODE_ENV
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - 5000:5000
volumes:
  data:
